apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-webpage-to-s3.fullname" . }}
  labels:
    {{- include "mcp-webpage-to-s3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mcp-webpage-to-s3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcp-webpage-to-s3.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mcp-webpage-to-s3.fullname" . }}