apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xianyu-agent.fullname" . }}
  labels:
    {{- include "xianyu-agent.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
  COOKIES_STR: {{ .Values.secrets.COOKIES_STR | b64enc | quote }}
