apiVersion: v2
name: grafana-stack
description: A Helm chart for Kubernetes

type: application
version: 1.0.1
appVersion: 1.0.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 27.1.0
    condition: prometheus.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 8.8.5
    condition: grafana.enabled
  - name: tempo
    repository: https://grafana.github.io/helm-charts
    version: 1.18.1
    condition: tempo.enabled
  - name: grafana-agent-operator
    alias: grafanaAgentOperator
    repository: https://grafana.github.io/helm-charts
    version: 0.5.0
    condition: grafanaAgentOperator.enabled