prometheus:
  enabled: true
  
  configmapReload:
    prometheus:
      enabled: false

  server:
    nodeSelector: {}

    persistentVolume:
      size: 8Gi

    resources: 
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi

    service:
      servicePort: 9090

  alertmanager:
    enabled: true

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

  prometheus-pushgateway:
    enabled: true

grafana:
  enabled: true
  replicas: 1
  assertNoLeakedSecrets: false
  fullnameOverride: grafana-stack-grafana

  image:
    repository: grafana/grafana-oss

  service:
    port: 3000

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  adminUser: admin
  adminPassword: admin

  grafana.ini:
    database: 
      type: mysql
      host: mysql.ns.svc
      name: grafana
      user: root
      password: root
      url: mysql://root:root@mysql.ns.svc:3306/grafana
      log_queries: true
      ssl_mode: false
    server:
      root_url: https://grafana.example.com
    auth.generic_oauth:
      enabled: true
      name: Keycloak-OAuth
      allow_sign_up: true
      scopes: openid email profile offline_access roles
      use_refresh_token: true
      auth_url: https://auth.example.com/realms/master/protocol/openid-connect/auth
      token_url: https://auth.example.com/realms/master/protocol/openid-connect/token
      api_url: https://auth.example.com/realms/master/protocol/openid-connect/userinfo
      client_id: client-grafana
      client_secret: xxx

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://grafana-stack-prometheus-server:9090
          access: proxy
          isDefault: true

tempo:
  enabled: false

grafanaAgentOperator:
  enabled: false