apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.fullname" . }}-server
  labels:
    {{- include "prefect-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prefect-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "prefect-server.labels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["prefect", "server", "start"]
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}