apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-{{ include "memos.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingressHostname }}`)
      kind: Rule
      services:
        - name: svc-{{ include "memos.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: wildcard-tls-certificate