nameOverride: moon-panel
fullnameOverride: moon-panel

backend: 
  replicaCount: 1

  image:
    repository: ghcr.io/phantommaa/sun-panel/backend
    pullPolicy: IfNotPresent
    tag: ""

  resources: 
    limits:
      cpu: 1000m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 20Mi

  tolerations: []

  affinity: {}

  appConfig:
    # Base configuration
    base:
      # Web run port. Default:3002
      http_port: 3002
      # Root URL
      root_url: http://moonpanel.example.com
      # Database driver [mysql/sqlite(Default)]
      database_drive: mysql
      # Enable static file server. Default:true
      enable_static_server: false
      # Enable system monitor feature. Default:true
      enable_monitor: false
      # Used as prefix to generate file url. For example, it will lookup to "/uploads/xxxx.png"
      url_prefix: /uploads/

    # MySQL configuration (valid when database_drive=mysql)
    mysql:
      host: 127.0.0.1
      port: 3306
      username: root
      password: root
      db_name: moonpanel
      wait_timeout: 100

    # Use rclone to store files. Both support local and remote storage
    rclone:
      # dir path of local or bucket of remote storage. this item config not belong to rclone
      type: s3
      bucket: bucket_name
      rclone.conf: |-
        # type = s3
        # provider = AWS
        # access_key_id = AK
        # secret_access_key = SK
        # endpoint = https://s3.ap-east-1.amazonaws.com
        # region = ap-east-1

        # type = s3
        # provider = Minio
        # access_key_id = AK
        # secret_access_key = SK
        # endpoint=http://minio.infra:9000

        # type=s3
        # provider = Alibaba
        # access_key_id = AK
        # secret_access_key = SK
        # endpoint = oss-cn-hangzhou.aliyuncs.com

    # JWT configuration
    jwt:
      # JWT secret key
      secret: your_secret_key
      # JWT token expiration time in hours, default: 72
      expire: 72

    # OAuth providers configuration
    oauth:
      # Enable OAuth login, default: false
      enable: false
      # List of OAuth providers
      providers: []
        # - name: github
        #   client_id: your_client_id
        #   client_secret: your_client_secret
        #   auth_url: https://github.com/login/oauth/authorize
        #   token_url: https://github.com/login/oauth/access_token
        #   user_info_url: https://api.github.com/user
        #   scopes: read:user
        #   field_mapping_identifier: login
        #   field_mapping_display_name: name
        #   field_mapping_email: email

frontend: 
  replicaCount: 1

  image:
    repository: ghcr.io/phantommaa/sun-panel/frontend
    pullPolicy: IfNotPresent
    tag: ""

  service:
    port: 3080

  ingress:
    enabled: true
    hostname: moonpanel.example.com
    
  resources: 
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 10Mi

  tolerations: []

  affinity: {}


site: 
  replicaCount: 1

  imagePullSecrets: []

  image:
    repository: ghcr.io/phantommaa/moonbox-site
    pullPolicy: Always
    tag: latest

  resources: 
    limits:
      cpu: 1000m
      memory: 20Mi
    requests:
      cpu: 100m
      memory: 10Mi

  tolerations: []

  affinity: {}

