nameOverride: moon-panel
fullnameOverride: moon-panel

backend: 
  replicaCount: 1

  image:
    repository: ghcr.io/phantommaa/sun-panel/backend
    pullPolicy: IfNotPresent
    tag: ""

  resources: 
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 20Mi

  mysql: 
    host: host_or_ip
    port: 3306
    username: root
    password: password
    db_name: moonpanel
  
  rclone: 
    provider: xxx # Minio, Alibaba, AWS, webdav, etc.
    access_key_id: AK
    secret_access_key: SK
    endpoint: example.com
    bucket: bucket
    region: 

  jwt:
    secret: replace_me
    expire: 72  # hours

frontend: 
  replicaCount: 1

  image:
    repository: ghcr.io/phantommaa/sun-panel/frontend
    pullPolicy: IfNotPresent
    tag: ""

  service:
    port: 3080

  ingress:
    enabled: true
    hostname: moonpanel.example.com
    
  resources: 
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 10Mi

  tolerations: []

  affinity: {}

