{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-{{ include "mcp-gateway.fullname" . }}
spec:
  # entryPoints:
  #   - websecure
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`)
      kind: Rule
      services:
        - name: {{ include "mcp-gateway.fullname" . }}
          port: {{ .Values.service.port }}
  # tls:
  #   secretName: wildcard-tls-certificate
{{- end }}