replicaCount: 1

image:
  repository: ghcr.io/phantommaa/freshmeat-agent
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

resources:
  limits: # Params required to run playwright safely
    cpu: 4000m
    memory: 2000Mi
  requests: 
    cpu: 50m
    memory: 64Mi

# Secret settings - these will be stored as Kubernetes secrets
secrets:
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  LLM_MODEL: ""
  COOKIES_STR: ""

nodeSelector: {}

tolerations: []

affinity: {}

# Prompts configuration
prompts:
  # If enabled, will mount prompts from ConfigMap instead of using built-in ones
  useConfigMap: false
  # Prompt files content
  files:
    classify.txt: |
      # Default classify prompt content
    common.txt: |
      # Default common prompt content
    expert.txt: |
      # Default expert prompt content
    general.txt: |
      # Default general prompt content
    bargain.txt: |
      # Default bargain prompt content