replicaCount: 1

image:
  repository: ghcr.io/phantommaa/freshmeat-agent
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
securityContext: {}

resources:
  limits: # Params required to run playwright safely
    cpu: 4000m
    memory: 2000Mi
  requests: 
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  base:
    log_level: INFO
  openai:
    api_key: ""
    base_url: ""
    model: ""
  xianyu:
    cookies: ""
    timeout: 30
    retry_times: 3

# Secret settings - these will be stored as Kubernetes secrets
secrets:
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  LLM_MODEL: ""
  COOKIES_STR: ""

# Prompts configuration
prompts:
  # Prompt files content. if empty, will use built-in prompts
  files:
    classify.txt: ""
    common.txt: ""
    tech.txt: ""
    general.txt: ""
    bargain.txt: ""