apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "blinko.fullname" . }}
  labels:
    {{- include "blinko.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blinko.selectorLabels" . | nindent 4 }}
