apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freshmeat-ai.fullname" . }}
  labels:
    {{- include "freshmeat-ai.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cm-config.yaml") . | sha256sum }}
    checksum/prompts: {{ include (print $.Template.BasePath "/cm-prompts.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "freshmeat-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freshmeat-ai.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-config.yaml") . | sha256sum }}
        checksum/prompts: {{ include (print $.Template.BasePath "/cm-prompts.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            {{- range $file := .Values.prompts.files }}
            - name: prompts-volume
              mountPath: /app/prompts/{{ $file }}
              subPath: {{ $file }}
            {{- end }}
            {{- if not (empty .Values.prompts.custom_txt) }}
            - name: prompts-volume-custom
              mountPath: /app/prompts/custom_txt
              subPath: custom_txt
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "freshmeat-ai.fullname" . }}-config
        - name: prompts-volume
          configMap:
            name: freshmeat-ai-prompts
        {{- if not (empty .Values.prompts.custom_txt) }}
        - name: prompts-volume-custom
          configMap:
            name: {{ include "freshmeat-ai.fullname" . }}-prompts-custom
        {{- end }}