apiVersion: v2
name: xianyu-agent
description: A Helm chart for XianyuAutoAgent - AI-powered customer service bot for Xianyu platform
type: application
version: 0.1.0
appVersion: v1.0.0
keywords:
  - xianyu
  - ai
  - customer-service
maintainers:
  - name: Your Name
    email: your.email@example.com
