replicaCount: 1

image:
  repository: ghcr.io/phantommaa/xianyu-auto-agent
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

resources:
  limits: 
    cpu: 2000m
    memory: 2000Mi
  requests: 
    cpu: 50m
    memory: 64Mi

# Secret settings - these will be stored as Kubernetes secrets
secrets:
  OPENAI_API_KEY: ""
  COOKIES_STR: ""

nodeSelector: {}

tolerations: []

affinity: {}