apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "DELETE"
      - "PUT"
      - "PATCH"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 3600

{{- if eq .Values.config.auth.enabled true }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: user-auth
spec:
  basicAuth:
    secret: traefik-auth-users
{{- end }}