apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moon-panel.fullname" . }}-backend-conf
data:
  conf.yaml: |-
{{ toYaml .Values.backend.appConfig | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moon-panel.fullname" . }}-frontend-conf
data:
  default.conf: |-
{{ include "moon-panel-frontend.conf" . | indent 4 }}