apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "moon-panel.fullname" . }}-backend
  labels:
    {{- include "moon-panel.labels-backend" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moon-panel.selectorLabels-backend" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "moon-panel.fullname" . }}-frontend
  labels:
    {{- include "moon-panel.labels-frontend" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moon-panel.selectorLabels-frontend" . | nindent 4 }}
