apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshmeat-agent.fullname" . }}-prompts-custom
  labels:
    {{- include "freshmeat-agent.labels" . | nindent 4 }}
data:
  {{- if not (empty .Values.prompts.custom_txt) }}
  custom_txt: |
    {{- .Values.prompts.custom_txt | nindent 4 }}
  {{- end }}