apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freshmeat-agent.fullname" . }}
  labels:
    {{- include "freshmeat-agent.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-prompts.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "freshmeat-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freshmeat-agent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-prompts.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "freshmeat-agent.fullname" . }}-secrets
          {{- if .Values.prompts.files }}
          volumeMounts:
            {{- range $key, $value := .Values.prompts.files }}
            {{- if not (empty $value) }}
            - name: prompts-volume
              mountPath: /app/prompts/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: prompts-volume
          configMap:
            name: {{ include "freshmeat-agent.fullname" . }}-prompts