replicaCount: 1

image:
  repository: ghcr.io/phantommaa/freshmeat-ai
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
securityContext: {}

resources:
  limits: # Params required to run playwright safely
    cpu: 4000m
    memory: 2000Mi
  requests: 
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  base:
    log_level: INFO
  xianyu:
    cookies: ""
  openai:
    api_key: your-secret-key
    base_url: https://openrouter.ai/api/v1/
    models:
      classify: google/gemini-2.0-flash-lite-001
      experts:
        tech: anthropic/claude-3.7-sonnet
        general: deepseek/deepseek-chat-v3-0324
        bargain: deepseek/deepseek-chat-v3-0324
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    db_name: freshmeat
    wait_timeout: 100

# Prompts configuration
prompts:
  # Prompt files
  files:
    - "classify_txt"
    - "bargain_txt"
    - "tech_txt"
    - "general_txt"
    - "common_txt"
  # Prompt words customized for individuals
  custom_txt: ""