apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "umami.fullname" . }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "umami.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "umami.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE_TYPE
              value: mysql
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl }}
            - name: APP_SECRET
              value: {{ .Values.appSecret }}